# Generated by Django 5.0.7 on 2024-10-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10),
        ),
    ]
